export const ACTION_EVENTS = {
	REMOVE_WISHLIST: 'REMOVE_FROM_WISHLIST',
	ADD_WISHLIST: 'ADD_TO_WISHLIST',
	ADD_CART: 'ADD_TO_CART',
	REMOVE_CART: 'REMOVE_FROM_CART',
	CREATE_ORDER: 'CREATE_NEW_ORDER',
}
